"""Add game reivew and curated review tables

Revision ID: 2e376d4dcadf
Revises: f0095d3770d3
Create Date: 2025-12-17 06:02:48.622788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e376d4dcadf'
down_revision: Union[str, Sequence[str], None] = 'f0095d3770d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('curatedcontent_ibfk_1'), 'curatedcontent', type_='foreignkey')
    op.create_foreign_key(None, 'curatedcontent', 'rawcontent', ['raw_content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rawcontent_ibfk_1'), 'rawcontent', type_='foreignkey')
    op.create_foreign_key(None, 'rawcontent', 'keyword', ['keyword_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasklog_ibfk_1'), 'tasklog', type_='foreignkey')
    op.create_foreign_key(None, 'tasklog', 'keyword', ['keyword_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasklog', type_='foreignkey')
    op.create_foreign_key(op.f('tasklog_ibfk_1'), 'tasklog', 'keyword', ['keyword_id'], ['id'])
    op.drop_constraint(None, 'rawcontent', type_='foreignkey')
    op.create_foreign_key(op.f('rawcontent_ibfk_1'), 'rawcontent', 'keyword', ['keyword_id'], ['id'])
    op.drop_constraint(None, 'curatedcontent', type_='foreignkey')
    op.create_foreign_key(op.f('curatedcontent_ibfk_1'), 'curatedcontent', 'rawcontent', ['raw_content_id'], ['id'])
    # ### end Alembic commands ###
