"""Create game review table

Revision ID: 3ac33635363b
Revises: 2db0e5490f19
Create Date: 2025-12-17 10:19:10.397578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac33635363b'
down_revision: Union[str, Sequence[str], None] = '2db0e5490f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_reviews_id'), 'game_reviews', ['id'], unique=False)
    op.create_table('curated_game_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_review_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('curated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_review_id'], ['game_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_game_reviews_id'), 'curated_game_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curated_game_reviews_id'), table_name='curated_game_reviews')
    op.drop_table('curated_game_reviews')
    op.drop_index(op.f('ix_game_reviews_id'), table_name='game_reviews')
    op.drop_table('game_reviews')
    # ### end Alembic commands ###
