"""Create remaining core tables

Revision ID: c93021f4e1bc
Revises: f697008bd951
Create Date: 2025-12-09 00:50:31.611741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c93021f4e1bc'
down_revision: Union[str, Sequence[str], None] = 'f697008bd951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_id'), 'keyword', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_keyword_text'), 'keyword', ['keyword_text'], unique=True)
    op.create_index(op.f('ix_keyword_user_id'), 'keyword', ['user_id'], unique=False)
    op.drop_index(op.f('ix_keyword_configs_id'), table_name='keyword_configs')
    op.drop_index(op.f('ix_keyword_configs_keyword_text'), table_name='keyword_configs')
    op.drop_index(op.f('ix_keyword_configs_user_id'), table_name='keyword_configs')
    op.drop_table('keyword_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_configs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_text', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_keyword_configs_user_id'), 'keyword_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_keyword_configs_keyword_text'), 'keyword_configs', ['keyword_text'], unique=True)
    op.create_index(op.f('ix_keyword_configs_id'), 'keyword_configs', ['id'], unique=False)
    op.drop_index(op.f('ix_keyword_user_id'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_keyword_text'), table_name='keyword')
    op.drop_index(op.f('ix_keyword_id'), table_name='keyword')
    op.drop_table('keyword')
    # ### end Alembic commands ###
