"""empty message

Revision ID: d1018de0f1f7
Revises: c93021f4e1bc
Create Date: 2025-12-09 04:31:24.672038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1018de0f1f7'
down_revision: Union[str, Sequence[str], None] = 'c93021f4e1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'updated_at')
    op.drop_column('keyword', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('keyword', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
