"""empty message

Revision ID: f0095d3770d3
Revises: d1018de0f1f7
Create Date: 2025-12-09 04:53:49.375256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0095d3770d3'
down_revision: Union[str, Sequence[str], None] = 'd1018de0f1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('rawcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rawcontent_id'), 'rawcontent', ['id'], unique=False)
    op.create_table('tasklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasklog_celery_task_id'), 'tasklog', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_tasklog_id'), 'tasklog', ['id'], unique=False)
    op.create_table('curatedcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_content_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('extracted_keywords', sa.Text(), nullable=False),
    sa.Column('curated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['raw_content_id'], ['rawcontent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curatedcontent_id'), 'curatedcontent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curatedcontent_id'), table_name='curatedcontent')
    op.drop_table('curatedcontent')
    op.drop_index(op.f('ix_tasklog_id'), table_name='tasklog')
    op.drop_index(op.f('ix_tasklog_celery_task_id'), table_name='tasklog')
    op.drop_table('tasklog')
    op.drop_index(op.f('ix_rawcontent_id'), table_name='rawcontent')
    op.drop_table('rawcontent')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
