"""Create initial Keyword table

Revision ID: f697008bd951
Revises: 
Create Date: 2025-12-08 11:09:10.485699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f697008bd951'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_configs_id'), 'keyword_configs', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_configs_keyword_text'), 'keyword_configs', ['keyword_text'], unique=True)
    op.create_index(op.f('ix_keyword_configs_user_id'), 'keyword_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_configs_user_id'), table_name='keyword_configs')
    op.drop_index(op.f('ix_keyword_configs_keyword_text'), table_name='keyword_configs')
    op.drop_index(op.f('ix_keyword_configs_id'), table_name='keyword_configs')
    op.drop_table('keyword_configs')
    # ### end Alembic commands ###
